### PR TITLE
Firebird services support

### PR DESCRIPTION
**Pull request by artyom-smirnov**
Low level services wire protocol implementation and wrappers for backup, nbackup, user and trace management

### CODE REVIEW

**Comment by artyom-smirnov** [comment]
This is WIP pull request. Before making it "ready to merge" I want to add maintenance management (repair, sweep, etc) and add some testing. If you have a some time, take a glance. May be you see it somehow different.

**Comment by bat22** [comment]
In my opinion:

- use `int` instead of `int16` here
```
type XPBReader struct {
	buf []byte
	pos int16
}
```

- Bytes() is more idiomatic name for
```
func (pb *XPBWriter) GetBuffer() []byte
```

- use `append()` instead of `bytes.Join()` in XPBWriter (with method Reset() object can be reused with existing buffer)


ps
what does XPB mean?

**Comment by artyom-smirnov** [comment]
> what does XPB mean?

Just common name name for DPB, RPB.

**Comment by bat22** [comment]
I think most likely case for XPBReader.Reset is reset with new byte slice
for example: https://pkg.go.dev/strings#Reader.Reset, https://pkg.go.dev/bytes#Reader.Reset

**Comment by nakagami** [comment]
Great Job!

I don't know much about the service API, but I think the code is good.
Test code is also good.

It would be even better if you could include an example in the README if possible, but I think I will merge it without the README when this work is completed.

**Comment by HelioNeto** [comment]
Hello, congratulations on the initiative, it will be great to have the backup/restore directly through the service port. It is now available for use. I tried to "go get" but I can't use it.
Thanks

**Comment by artyom-smirnov** [comment]
> Hello, congratulations on the initiative, it will be great to have the backup/restore directly through the service port. It is now available for use. I tried to "go get" but I can't use it. Thanks

Hi! I was bit busy with work and did not finished this patch so this is still WIP. I will be happy if it will be feature which will be useful to someone. Will try to complete work in near time!

**Comment by HelioNeto** [comment]
> Hi! I was bit busy with work and did not finished this patch so this is still WIP. I will be happy if it will be feature which will be useful to someone. Will try to complete work in near time!

No problem friend, if it's just because of me, don't worry, I'm still testing the Go language and I don't have any real projects yet.
but this feature will add a lot to the community, I already use Firebird in other languages ​​and using the "Service Port" avoids the need to use "gbak".
Thanks again.

**Comment by artyom-smirnov** [comment]
Shame I have not much time to complete this PR early. I think it mostly complete now. I have added tests and some examples how to work with service manager. @nakagami if it looks OK to you please merge. Will be glad to hear any critics from anyone.

**Comment by nakagami** [comment]
I have been waiting for your pull request, Thank you !

I'm not sure about the service API, but it doesn't seem to harm the existing code, so I'll merge it and wait for feedback from other developpers.

**Pull request merged**
