### PR TITLE
Correct size of column returned by buffer

### LINKED ISSUE #117: Incorrect length for CHAR
The string length returned by query selecting a CHAR column is exactly 4 times of size of column.

To reproduce the problem:

```go
package main

import (
	"database/sql"
	"fmt"
	"log"
	"net/url"

	_ "github.com/nakagami/firebirdsql"
)

func main() {
	//connecto to DB
	db, err := connectFirebird("localhost", "firebird/data/testdb", "usr", "password", 3050)
	if err != nil {
		panic(err)
	}

	defer db.Close()

	tableName := "ISSUEX"

	queryDrop := `drop table "` + tableName + `";`

	db.Exec(queryDrop)

	// modify this len
	charLen := 52

	queryCreate := fmt.Sprintf("CREATE TABLE %s (A CHAR(%d))", tableName, charLen)

	_, err = db.Exec(queryCreate)
	if err != nil {
		panic(err)
	}

	defer db.Exec(queryDrop)

	queryInsert := `insert into ` + tableName + ` (A) values ('Dixer')`

	_, err = db.Exec(queryInsert)
	if err != nil {
		panic(err)
	}

	var t string
	if err := db.QueryRow(`SELECT A FROM ` + tableName).Scan(&t); err != nil {
		panic(err)
	}

	if len(t) != charLen {
		log.Fatalf("ERROR: Length expected: %d, Returned: %d", charLen, len(t))
	}

	log.Printf("SUCCESS: Data: %s, Len: %d\n\n", t, len(t))
}

//connectFirebird : Conectar a la base de datos Firebird
func connectFirebird(host, database, username, password string, port int) (*sql.DB, error) {

	// default port
	if port == 0 {
		port = 3050
	}

	//Password in firebird dsn not accept spaces, so escape with url.QueryEscape

	// in form user:pass@host:port/database
	dsn := fmt.Sprintf("%s:%s@%s:%d/%s", username, url.QueryEscape(password), host, port, database)

	db, err := sql.Open("firebirdsql", dsn)

	if err != nil {
		return nil, err
	}

	err = db.Ping()

	if err != nil {
		return nil, err
	}

	return db, nil
}
```

Tested with Firebird 2.5.9 and 3.0.7 on:
- linux/amd64
- linux/arm64
- darwin/amd64
- windows/amd64

### PR DESCRIPTION
**Pull request by xhit**
Fix #117

### CODE REVIEW

**Comment by nakagami** [comment]
One character is 4 bytes in utf-8, but not in other character encodings.
we have to change the divide value depending on the character encoding, but
I wonder if I can simply divide by 4?

Isn't it better to return the number of bytes instead of the number of characters, as it is now?

**Comment by xhit** [comment]
> For CHAR is fixed, but FirebirdSQL maybe returns the **size of column * max len used by charset by character** (in this case, 4 bytes for UTF-8).

Tested. The sentence is true.

The length returned in buffer depends on charset set in connection string with `charset` param.

For example, with code in #117 and setting `charLen := 5`:

* With `?charset=BIG_5` the length is 10 because BIG_5 character length is 2.
* With `?charset=ISO8859_13` the length is 5 because ISO8859_13 character length is 1.

So, this driver should handle encoding to get the correct length.

**Comment by xhit** [comment]
@nakagami done. PTAL.

**Comment by nakagami** [comment]
Thanks, It seems good

**Pull request merged**
