### PR TITLE
Pooling

### PR DESCRIPTION
**Pull request by NilsKrause**
* Implement requirements for the database/sql pooling functionality.
* Driver now reconnects automaticly when the database is ready again.
* Returning concrete errors from wireprotocol for better error handling.

### CODE REVIEW

**Comment by NilsKrause** [comment]
Test failed because the number of function arguments changed. DSN is not parsed into firebirdDsn type to comply with the database/sql.Connector interface.
https://golang.org/pkg/database/sql/driver/#Connector

Gonna change the tests tomorrow. And add the commit to the PR.

**Comment by NilsKrause** [comment]
Okay, should be running smoothly now.

**Comment by nakagami** [comment]
Thanks, it seems very good to me.

But I hope someone's review. Or vote.

**Comment by NilsKrause** [comment]
Oh and also this should fix issue #29

**Comment by nakagami** [comment]
Umm, It seems very good to me!
Thanks, Nils.

**Pull request merged**
